/* Auto generated by typedotenv */
if (typeof import.meta.env.VITE_DESCRIPTION !== 'string') throw new Error('VITE_DESCRIPTION is not defined in .env');
export const VITE_DESCRIPTION = import.meta.env.VITE_DESCRIPTION;
