name: Checks
on:
  push:
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  check:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - run: pnpm check
      - run: pnpm build
